### ISSUE TITLE
What does this package do?

### ISSUE THREAD

**Issue by wyuenho** [jcs-elpa/company-quickhelp-terminal#1]
What does this package do? There's no motivation in the README. Also, why is it completely overriding `company-quickhelp--show`? Won't this eventually diverge from `company-quickhelp` ? If that's the case, why not just submit a PR to `company-quickhelp` to do what you want to do?

**Comment by jcs090218** [comment]
Refer to this

https://github.com/company-mode/company-quickhelp/pull/100

and

https://github.com/company-mode/company-quickhelp/issues/99

. They have rejected and doesn't want the terminal supports. Hence, this is an ugly solution but works. I really want this to be merged but no luck due to the original author from `company-quickhelp`. 😞

**Comment by wyuenho** [comment]
Emacs shouldn't be used in terminal ROFL.

**Comment by jcs090218** [comment]
Well, if you never have to work in terminal then is great. When your work requires you to work in terminal. Good luck with vim or nano! lol
